### ISSUE TITLE
compatibility with refactored Hydra

### ISSUE THREAD

**Issue by akhedrane** [ory-am/hydra-idp-postgres#1]
Hi,
i want thank you for great work you do in hydra,
We need full-featured identity management service with AuthN and AuthZ.
i see that main hydra repo refactored to be authN+authZ solution on top of OAuth2 & OIDC, and this repo provide users management for postgres database.
So is this idp compatible with refactor made in main Hydra repo?
if not, when will be?

**Comment by aeneasr** [comment]
Hey, thank you for your question. Hydra has been completely refactored and does not require a specific API. This repository is therefore outdated. I am currently in the process of writing an exemplary react identity provider that works with hydra: https://github.com/ory-am/hydra-idp-react

You can read more on this topic here (be aware that the documentation is work in progress): https://ory-am.gitbooks.io/hydra/content/oauth2.html
